//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPE.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Donor
    {
        public int ID { get; set; }

        [DisplayName("Name")]
        [Required(ErrorMessage = "This name is required")]
        [RegularExpression("^[a-zA-Z ]+$", ErrorMessage = "only alphabet ")]
        public string name { get; set; }

        [DisplayName("Email")]
        [Required(ErrorMessage = "This email is required")]
        [StringLength(40, ErrorMessage = "Do not enter more than 40 characters")]
        [RegularExpression(@"^[a-zA-Z0-9]+@[a-zA-Z0-9]+(.[a-zA-Z]+)$", ErrorMessage = "Email is not valid")]
        public string email { get; set; }

        [DisplayName("Address")]
        [Required(ErrorMessage = "This address is required")]
        [StringLength(40, ErrorMessage = "Do not enter more than 40 characters")]
        [RegularExpression(@"^[0-9a-zA-Z''-'\s]{1,40}$", ErrorMessage = "special characters are not allowed.")]
        public string address { get; set; }

        [DisplayName("Home Phone")]
        [RegularExpression(@"^[0-9]*$", ErrorMessage = "Please only enter number")]
        [StringLength(15, ErrorMessage = "Do not enter more than 15 number")]
        public string homePhone { get; set; }

        [DisplayName("Mobile Phone")]
        [Required(ErrorMessage = "This mobilephone is required"), MinLength(7), MaxLength(15)]
        [RegularExpression(@"^[0-9]*$", ErrorMessage = "Please only enter number")]
        public string mobilePhone { get; set; }

        [DisplayName("Date of Birth")]
        [StringLength(15, ErrorMessage = "Do not enter more than 15 number")]
        [RegularExpression("^([0]?[1-9]|[1|2][0-9]|[3][0|1])[./-]([0]?[1-9]|[1][0-2])[./-]([0-9]{4}|[0-9]{2})$", ErrorMessage = "Date of Birth is invalid ")]
        public string dateOfBirth { get; set; }
    }
}
